DIR_ssp = '/afs/mpa/data/vwild/bc03/models/Padova1994/chabrier/'
DIR_csp = '/afs/mpa/data/vwild/bc03/models/Padova1994/chabrier_out/'
DIR_pca = '/afs/mpa/data/vwild/bc03/PCA/'
DIR_lib = '/scratch/vwild/bc03_lib/'
;DIR_ran_in = '/afs/mpa/sim/users/blaizot/PCA_N_SAMs/RAND_SFH/'
;DIR_ran_in = '/scratch/RAND_SFH/'

DIR_ran_in =  dir_pca_data+'MRUN/RANDOM_stuff/SFH/'
DIR_ran_out = dir_pca_data+'bc03/RAN_JB/'
